#!/bin/env python3
# Created by atbswp (https://github.com/rmpr/atbswp)
# on 14 Jul 2020 
import pyautogui
import time
pyautogui.FAILSAFE = False

#Bloco 4
pyautogui.mouseDown(2054, 1079, 'left')
pyautogui.mouseUp(2054, 1079, 'left')
# Sair workflowpag-authentication-app e Entrar workflowpag-front
time.sleep(1)
pyautogui.keyDown('c')
pyautogui.keyDown('d')
pyautogui.keyUp('c')
pyautogui.keyUp('d')
pyautogui.keyDown('space')
pyautogui.keyUp('space')
pyautogui.keyDown('.')
pyautogui.keyUp('.')
pyautogui.keyDown('.')
pyautogui.keyUp('.')
pyautogui.keyDown('/')
pyautogui.keyUp('/')
pyautogui.keyDown('a')
pyautogui.keyUp('a')
pyautogui.keyDown('u')
pyautogui.keyUp('u')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
time.sleep(1)
pyautogui.keyDown('w')
pyautogui.keyUp('w')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
time.sleep(1)
pyautogui.keyDown('p')
pyautogui.keyUp('p')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
time.sleep(1)
# Bloco 3
pyautogui.mouseDown(1788, 993, 'left')
pyautogui.mouseUp(1788, 993, 'left')
# Sair workflowpag-authentication-app e Entrar workflowpag-front
pyautogui.keyDown('ctrlleft')
pyautogui.keyDown('c')
pyautogui.keyUp('c')
pyautogui.keyUp('ctrlleft')
time.sleep(2)
pyautogui.keyDown('c')
pyautogui.keyDown('d')
pyautogui.keyUp('c')
pyautogui.keyUp('d')
pyautogui.keyDown('space')
pyautogui.keyUp('space')
pyautogui.keyDown('.')
pyautogui.keyUp('.')
pyautogui.keyDown('.')
pyautogui.keyUp('.')
pyautogui.keyDown('/')
pyautogui.keyUp('/')
pyautogui.keyDown('a')
pyautogui.keyUp('a')
pyautogui.keyDown('u')
pyautogui.keyUp('u')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
time.sleep(1)
pyautogui.keyDown('w')
pyautogui.keyUp('w')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
time.sleep(1)
pyautogui.keyDown('p')
pyautogui.keyUp('p')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
time.sleep(1)
# comando: 'yarn dev'
pyautogui.keyDown('y')
pyautogui.keyUp('y')
pyautogui.keyDown('a')
pyautogui.keyUp('a')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('space')
pyautogui.keyUp('space')
pyautogui.keyDown('d')
pyautogui.keyUp('d')
pyautogui.keyDown('e')
pyautogui.keyUp('e')
pyautogui.keyDown('v')
pyautogui.keyUp('v')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
time.sleep(1)
# Bloco 2
pyautogui.mouseDown(2434, 486, 'left')
pyautogui.mouseUp(2434, 486, 'left')
# Descer docker
pyautogui.keyDown('d')
pyautogui.keyUp('d')
pyautogui.keyDown('o')
pyautogui.keyUp('o')
pyautogui.keyDown('c')
pyautogui.keyUp('c')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('-')
pyautogui.keyUp('-')
pyautogui.keyDown('c')
pyautogui.keyUp('c')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('d')
pyautogui.keyUp('d')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
time.sleep(10)
# Sair workflowpag-authentication-api e Entrar workflowpag-api
pyautogui.keyDown('c')
pyautogui.keyDown('d')
pyautogui.keyUp('c')
pyautogui.keyUp('d')
pyautogui.keyDown('space')
pyautogui.keyUp('space')
pyautogui.keyDown('.')
pyautogui.keyUp('.')
pyautogui.keyDown('.')
pyautogui.keyUp('.')
pyautogui.keyDown('/')
pyautogui.keyUp('/')
pyautogui.keyDown('a')
pyautogui.keyUp('a')
pyautogui.keyDown('u')
pyautogui.keyUp('u')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
time.sleep(1)
pyautogui.keyDown('w')
pyautogui.keyUp('w')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
time.sleep(1)
pyautogui.keyDown('i')
pyautogui.keyUp('i')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
# subir docker-compose
pyautogui.keyDown('d')
pyautogui.keyUp('d')
pyautogui.keyDown('o')
pyautogui.keyUp('o')
pyautogui.keyDown('c')
pyautogui.keyUp('c')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('-')
pyautogui.keyUp('-')
pyautogui.keyDown('c')
pyautogui.keyUp('c')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('u')
pyautogui.keyUp('u')
pyautogui.keyDown('p')
pyautogui.keyUp('p')
pyautogui.keyDown('space')
pyautogui.keyUp('space')
pyautogui.keyDown('-')
pyautogui.keyUp('-')
pyautogui.keyDown('-')
pyautogui.keyUp('-')
pyautogui.keyDown('b')
pyautogui.keyUp('b')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyDown('-')
pyautogui.keyUp('-')
pyautogui.keyDown('d')
pyautogui.keyUp('d')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
time.sleep(4)
# Bloco 4
pyautogui.mouseDown(2054, 1079, 'left')
pyautogui.mouseUp(2054, 1079, 'left')
# Abri VisualCode
pyautogui.keyDown('c')
pyautogui.keyUp('c')
pyautogui.keyDown('o')
pyautogui.keyUp('o')
pyautogui.keyDown('d')
pyautogui.keyDown('e')
pyautogui.keyUp('d')
pyautogui.keyUp('e')
pyautogui.keyDown('space')
pyautogui.keyUp('space')
pyautogui.keyDown('.')
pyautogui.keyUp('.')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
time.sleep(3)
pyautogui.keyDown('winleft')
pyautogui.keyDown('left')
pyautogui.keyUp('left')
pyautogui.keyUp('winleft')
time.sleep(2)
